//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KirtasiyeDunayasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KISI
    {
        public int KisiID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string KisiRolu { get; set; }
        public string Email { get; set; }
        public string Parola { get; set; }
    
        public virtual Admin_ Admin_ { get; set; }
        public virtual KULLANCILAR KULLANCILAR { get; set; }
    }
}
