//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KirtasiyeDunayasi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KirtasiyeParkEntities1 : DbContext
    {
        public KirtasiyeParkEntities1()
            : base("name=KirtasiyeParkEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_> Admin_ { get; set; }
        public virtual DbSet<Fatura> Faturas { get; set; }
        public virtual DbSet<Indirim> Indirims { get; set; }
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<KISI> KISIs { get; set; }
        public virtual DbSet<KULLANCILAR> KULLANCILARs { get; set; }
        public virtual DbSet<Marka> Markas { get; set; }
        public virtual DbSet<OdemeYonetimi> OdemeYonetimis { get; set; }
        public virtual DbSet<Sipari> Siparis { get; set; }
        public virtual DbSet<SiparisUrun> SiparisUruns { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Urun> Uruns { get; set; }
        public virtual DbSet<Yorum> Yorums { get; set; }
    }
}
